
# Inserts a blank line between shell prompts
add_newline = false
format = "$username$hostname$character"
right_format = "$all"

[character]
success_symbol = '[](bold white)'
error_symbol = '[✗](bold red)'
vicmd_symbol = "[V](bold green)"

[directory]
truncation_length = 1

[hostname]
ssh_only = false
format = '[@](bold red)[$hostname](bold white)\]'
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = '\[[$user]($style)'
disabled = false
show_always = true
