require "niksingh710.general"
require "niksingh710.options"
require "niksingh710.plugins"
require "niksingh710.dashboard"
require "niksingh710.telescope"
require "niksingh710.whichkey"
require "niksingh710.keymaps"
require "niksingh710.autocommands"
