#!/bin/bash
# These are the scripts and files created by Nikhil Singh <nik.singh710@gmail.com>
#            _   ________ __ __  ________   _      
#           / | / /  _/ //_// / / /  _/ /  ( )_____
#          /  |/ // // ,<  / /_/ // // /   |// ___/
#         / /|  // // /| |/ __  // // /___  (__  ) 
#        /_/ |_/___/_/ |_/_/ /_/___/_____/ /____/  
#                                                  
#             ______            _____           
#            / ____/___  ____  / __(_)___ ______
#           / /   / __ \/ __ \/ /_/ / __ `/ ___/
#          / /___/ /_/ / / / / __/ / /_/ (__  ) 
#          \____/\____/_/ /_/_/ /_/\__, /____/  
#                                 /____/        
#                                     __
#                    ____ _____  ____/ /
#                   / __ `/ __ \/ __  / 
#                  / /_/ / / / / /_/ /  
#                  \__,_/_/ /_/\__,_/   
#                                       
#              _____           _       __      
#             / ___/__________(_)___  / /______
#             \__ \/ ___/ ___/ / __ \/ __/ ___/
#            ___/ / /__/ /  / / /_/ / /_(__  ) 
#           /____/\___/_/  /_/ .___/\__/____/  
#                           /_/                
# (niksingh710) [https://github.com/niksingh710] [https://t.me/niksingh710]

CPUSTAT=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
if [ -f /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ];then
  if [ $CPUSTAT = 'performance' ];then
    eval "/home/niksingh710/Personal/bin/cpu-powr"
  else
    eval "/home/niksingh710/Personal/bin/cpu-perf"
  fi
    CPUTURBO="Unable to get Status"
    if [ -f "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor" ];then
      CPUTURBO=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
    fi
    hash notify-send 2>/dev/null && notify-send -u normal -i cpu -a Toggle-CPU "Current CPU status" "$(echo -e $CPUTURBO)"
else
  hash notify-send 2>/dev/null && notify-send -u normal -i Err -a cpu-stat "CPU File" "The file does not exist" 
fi
